### ISSUE TITLE
Related to video Page

### ISSUE THREAD

**Issue by inzamamahmad3** [safak/youtube2022#123]
When I click on the video on the home page. It shows me an error.
"Cannot read properties of null (reading 'videoUrl')
TypeError: Cannot read properties of null (reading 'videoUrl')
    at Video (http://localhost:3000/static/js/bundle.js:2772:29)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:61326:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:64612:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:65908:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:50918:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:50962:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:51019:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:70893:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:70140:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:70063:9)
"

Anyone how to solve this

**Comment by jihacshnu** [comment]
It happens sometime when you delete the data related to property from database. Like we would have deleted one url from database. I have faced same error in my chat app when I have accidentally deleted a chat. I have resolved that issue by removing the whole user from database and sign in again.
