### ISSUE TITLE
How to solve this

### ISSUE THREAD

**Issue by roopikaik** [safak/youtube2022#146]
Unexpected Application Error!
Objects are not valid as a React child (found: object with keys {code, errno, sqlMessage, sqlState, fatal}). If you meant to render a collection of children, use an array instead.
Error: Objects are not valid as a React child (found: object with keys {code, errno, sqlMessage, sqlState, fatal}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:3000/static/js/bundle.js:39985:13)
    at updateSlot (http://localhost:3000/static/js/bundle.js:40249:11)
    at reconcileChildrenArray (http://localhost:3000/static/js/bundle.js:40369:26)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:40756:20)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:45183:32)
    at updateHostComponent (http://localhost:3000/static/js/bundle.js:45827:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:47279:18)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:52214:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:51484:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:51407:9)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.

**Comment by 6TBabuska** [comment]
u r sending data as object thats the error.
