### ISSUE TITLE
Getting undefined error in chats.jsx

### ISSUE THREAD

**Issue by yatharthdwivedi** [safak/youtube2022#88]

**Comment by yatharthdwivedi** [comment]
react-dom.development.js:26740 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Chats (Chats.jsx:34:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at updateFunctionComponent (react-dom.development.js:20313:1)
    at beginWork (react-dom.development.js:22356:1)
    at beginWork$1 (react-dom.development.js:27219:1)
    at performUnitOfWork (react-dom.development.js:26392:1)
    at workLoopSync (react-dom.development.js:26303:1)
    at renderRootSync (react-dom.development.js:26271:1)
    at recoverFromConcurrentError (react-dom.development.js:25689:1)

**Comment by jennatark** [comment]
im getting a similar error as well

**Comment by Mohd-Samad-Siddiqui** [comment]
Same error

**Comment by NisooJadhav** [comment]
@yatharthdwivedi, simply change the code 

`Object.entries(chats)` to `Object.entries(chats || {})` 

at your line 34 and the error will be gone
